# First run
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env && docker-compose up -d && docker-compose exec -d dockovpn wget -O /doc/Dockovpn/client.ovpn localhost:8080

version: '3'
services:
  dockovpn:
    build:
      context: .
    cap_add:
        - NET_ADMIN
    ports:
        - 1194:1194/udp
    volumes:
        - openvpn_conf:/opt/Dockovpn_data
    restart: always

volumes:
  openvpn_conf:
